import Footer from "./components/Footer/Footer";
import Navbar from "./components/Navbar/Navbar";
import "./globals.css";
import Providers from "./lib/Providers";

export const metadata = {
  title: "Mine Vault",
  description: "Generated by Mine Vault",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="max-w-[2000px] mx-auto">
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
